import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './Global Redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
   
        
        </body>
    </html>
  )
}
